  WARNING: The scripts f2py and numpy-config are installed in '/home/hhao9/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools, pyftmerge, pyftsubset and ttx are installed in '/home/hhao9/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/home/hhao9/.local/lib/python3.9/site-packages)
Traceback (most recent call last):
  File "/var/lib/condor/execute/slot1/dir_3847219/./eval_cp.py", line 5, in <module>
    import conjugate_priors_alg 
  File "/var/lib/condor/execute/slot1/dir_3847219/conjugate_priors_alg.py", line 3, in <module>
    import new_utils
  File "/var/lib/condor/execute/slot1/dir_3847219/new_utils.py", line 5, in <module>
    from scipy.stats import kendalltau
  File "/home/hhao9/.local/lib/python3.9/site-packages/scipy/stats/__init__.py", line 606, in <module>
    from ._stats_py import *
  File "/home/hhao9/.local/lib/python3.9/site-packages/scipy/stats/_stats_py.py", line 37, in <module>
    from scipy import sparse
  File "/home/hhao9/.local/lib/python3.9/site-packages/scipy/__init__.py", line 134, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/hhao9/.local/lib/python3.9/site-packages/scipy/sparse/__init__.py", line 294, in <module>
    from ._base import *
  File "/home/hhao9/.local/lib/python3.9/site-packages/scipy/sparse/_base.py", line 5, in <module>
    from scipy._lib._util import VisibleDeprecationWarning
  File "/home/hhao9/.local/lib/python3.9/site-packages/scipy/_lib/_util.py", line 18, in <module>
    from scipy._lib._array_api import array_namespace
  File "/home/hhao9/.local/lib/python3.9/site-packages/scipy/_lib/_array_api.py", line 17, in <module>
    from scipy._lib.array_api_compat import (
  File "/home/hhao9/.local/lib/python3.9/site-packages/scipy/_lib/array_api_compat/numpy/__init__.py", line 1, in <module>
    from numpy import *
  File "/home/hhao9/.local/lib/python3.9/site-packages/numpy/__init__.py", line 358, in __getattr__
    import numpy.f2py as f2py
  File "/home/hhao9/.local/lib/python3.9/site-packages/numpy/f2py/__init__.py", line 19, in <module>
  File "/home/hhao9/.local/lib/python3.9/site-packages/numpy/f2py/f2py2e.py", line 24, in <module>
ImportError: cannot import name 'rules' from partially initialized module 'numpy.f2py' (most likely due to a circular import) (/home/hhao9/.local/lib/python3.9/site-packages/numpy/f2py/__init__.py)
